import Foundation

/// Minimal i18n, mirroring web/src/lib/i18n.ts: 'de' holds the app's original
/// wording verbatim; every other language falls back de -> key so a missing
/// translation never renders a blank.
///
/// The selected language lives in UserDefaults under "maps.lang" (written by
/// @AppStorage("maps.lang") / AppModel.lang). Views re-render live because
/// AppModel republishes the value; `t` always reads the current selection.
enum L {
    static let supported = ["de", "en", "fr", "es", "it", "nl", "pl", "tr"]

    struct Language: Identifiable {
        let id: String
        let name: String
    }

    /// Endonyms — deliberately not translated (same as the web menu).
    static let languages: [Language] = [
        .init(id: "de", name: "Deutsch"), .init(id: "en", name: "English"),
        .init(id: "fr", name: "Français"), .init(id: "es", name: "Español"),
        .init(id: "it", name: "Italiano"), .init(id: "nl", name: "Nederlands"),
        .init(id: "pl", name: "Polski"), .init(id: "tr", name: "Türkçe"),
    ]

    /// First system language that we ship, else English.
    static var defaultLang: String {
        for pref in Locale.preferredLanguages {
            let code = String(pref.prefix(2)).lowercased()
            if supported.contains(code) { return code }
        }
        return "en"
    }

    /// Current language, as stored by @AppStorage("maps.lang").
    static var current: String {
        UserDefaults.standard.string(forKey: "maps.lang") ?? defaultLang
    }

    static func t(_ key: String) -> String {
        let dict = dicts[current] ?? de
        return dict[key] ?? de[key] ?? key
    }

    // MARK: - Dictionaries

    private static let de: [String: String] = [
        "cancel": "Abbrechen",
        "done": "Fertig",
        "more": "Mehr",
        "close": "Schließen",
        "retry": "Erneut versuchen",
        "language": "Sprache",
        "account": "Konto",
        "sign-in": "Anmelden",
        "sign-out": "Abmelden",
        "map-style": "Karten-Stil",
        "saved-places": "Gespeicherte Orte",
        "my-location": "Mein Standort",
        "view-3d": "3D-Ansicht",
        "map-load-failed": "Karte konnte nicht geladen werden.",

        "search-placeholder": "Ort, Adresse suchen …",
        "search-clear": "Suche löschen",
        "recent-searches": "Zuletzt gesucht",
        "results": "Ergebnisse",
        "unknown-place": "Unbekannter Ort",

        "route-to-here": "Route hierhin",
        "share-place": "Ort teilen",
        "save-place": "Ort speichern",
        "saved-remove": "Gespeichert — entfernen",

        "route-pick-start": "Startpunkt wählen: suchen oder Karte antippen …",
        "route-swap": "Start und Ziel tauschen",
        "route-loading": "Route wird berechnet …",
        "route-err-no-location": "Standort nicht verfügbar — Startpunkt wählen oder Standortzugriff erlauben.",
        "route-err-not-found": "Keine Route gefunden.",
        "route-err-unavailable": "Routenberechnung derzeit nicht verfügbar.",
        "nav-start": "Navigation starten",
        "nav-stop": "Navigation beenden",
        "nav-continue": "Weiter",
        "off-route": "Abseits der Route — neu berechnen …",
        "current-position": "Aktuelle Position",
        "mode-car": "Auto",
        "mode-bike": "Fahrrad",
        "mode-foot": "Zu Fuß",

        "saved-signin-hint": "Melde dich an, um Orte zu speichern und auf allen Geräten zu sehen.",
        "saved-empty": "Noch nichts gespeichert. Suche einen Ort und tippe auf den Stern.",
        "delete": "Löschen",

        "install": "Installieren",
        "remove": "entfernen",
        "name": "Name",
        "pack-install-title": "Texture-Pack installieren",
        "pack-install-hint": "Ein Pack ist ein MapLibre-Style (style.json). Packs können externe Kacheln/Schriften laden — nur aus vertrauenswürdigen Quellen installieren.",
        "pack-install-name-placeholder": "z. B. Neon Nights",
        "tab-from-url": "Von URL",
        "tab-paste-json": "JSON einfügen",
        "style-url-label": "Style-URL (https)",
        "style-json-label": "style.json Inhalt",
        "packs-signin-hint": "Zum Installieren eigener Packs anmelden.",
        "pack-install-failed": "Installation fehlgeschlagen — bitte erneut versuchen.",
        "err-invalid-name": "Bitte einen Namen (max. 60 Zeichen) angeben.",
        "err-invalid-url": "Die URL ist ungültig.",
        "err-url-https": "Nur https-URLs sind erlaubt.",
        "err-style-not-json": "Das ist kein gültiges JSON.",
        "err-style-version": "Der Style muss \"version\": 8 haben (MapLibre Style Spec).",
        "err-style-layers": "Dem Style fehlt das \"layers\"-Array.",
        "err-style-sources": "Dem Style fehlt das \"sources\"-Objekt.",
        "err-style-too-large": "Der Style ist zu groß (max. 512 KB).",
        "err-pack-limit": "Maximal 20 eigene Packs.",

        "register": "Registrieren",
        "email": "E-Mail",
        "password": "Passwort",
        "password-min8": "Passwort (min. 8 Zeichen)",
        "err-invalid-email": "Bitte eine gültige E-Mail-Adresse eingeben.",
        "err-password-too-short": "Passwort muss mindestens 8 Zeichen haben.",
        "err-email-taken": "Diese E-Mail ist bereits registriert.",
        "err-invalid-credentials": "E-Mail oder Passwort ist falsch.",
        "err-too-many-requests": "Zu viele Versuche — bitte kurz warten.",
        "err-unknown": "Etwas ist schiefgelaufen — bitte erneut versuchen.",

        "cat-restaurant": "Restaurants",
        "cat-cafe": "Cafés",
        "cat-supermarket": "Supermärkte",
        "cat-fuel": "Tankstellen",
        "cat-pharmacy": "Apotheken",
        "cat-hotel": "Hotels",
        "cat-parking": "Parken",
        "cat-atm": "Geldautomaten",
        "search-this-area": "Diesen Bereich durchsuchen",
        "race-mode": "Rennen",
        "race-start": "Rennen starten",
        "free-drive": "Freies Fahren",
        "free-drive-start": "Losfahren",
        "free-drive-hint": "Frei fahren — Touch-Pads. Keine Route nötig.",
        "race-pause": "Pause",
        "race-resume": "Weiter",
        "race-finish": "Ziel",
        "race-again": "Nochmal",
        "race-brake": "Bremse",
        "race-go": "Gas",
        "race-left": "Links",
        "race-right": "Rechts",
        "race-hint": "Kamera folgt dem Auto in Straßenansicht. Touch-Pads zum Fahren.",
        "race-countdown": "Start in",
        "race-complete": "Lauf fertig",
        "race-recent": "Letzte Läufe",
        "race-active-hint": "Rennmodus aktiv — HUD auf der Karte.",
        "race-empty-runs": "Noch keine Läufe.",
    ]

    private static let en: [String: String] = [
        "cancel": "Cancel",
        "done": "Done",
        "more": "More",
        "close": "Close",
        "retry": "Try again",
        "language": "Language",
        "account": "Account",
        "sign-in": "Sign in",
        "sign-out": "Sign out",
        "map-style": "Map style",
        "saved-places": "Saved places",
        "my-location": "My location",
        "view-3d": "3D view",
        "map-load-failed": "Map could not be loaded.",

        "search-placeholder": "Search place, address …",
        "search-clear": "Clear search",
        "recent-searches": "Recent searches",
        "results": "Results",
        "unknown-place": "Unknown place",

        "route-to-here": "Directions here",
        "share-place": "Share place",
        "save-place": "Save place",
        "saved-remove": "Saved — remove",

        "route-pick-start": "Choose a starting point: search or tap the map …",
        "route-swap": "Swap start and destination",
        "route-loading": "Calculating route …",
        "route-err-no-location": "Location unavailable — choose a starting point or allow location access.",
        "route-err-not-found": "No route found.",
        "route-err-unavailable": "Route calculation is currently unavailable.",
        "nav-start": "Start navigation",
        "nav-stop": "End navigation",
        "nav-continue": "Continue",
        "off-route": "Off route — recalculating …",
        "current-position": "Current position",
        "mode-car": "Car",
        "mode-bike": "Bike",
        "mode-foot": "On foot",

        "saved-signin-hint": "Sign in to save places and see them on all your devices.",
        "saved-empty": "Nothing saved yet. Search for a place and tap the star.",
        "delete": "Delete",

        "install": "Install",
        "remove": "remove",
        "name": "Name",
        "pack-install-title": "Install texture pack",
        "pack-install-hint": "A pack is a MapLibre style (style.json). Packs can load external tiles/fonts — only install styles from sources you trust.",
        "pack-install-name-placeholder": "e.g. Neon Nights",
        "tab-from-url": "From URL",
        "tab-paste-json": "Paste JSON",
        "style-url-label": "Style URL (https)",
        "style-json-label": "style.json content",
        "packs-signin-hint": "Sign in to install your own packs.",
        "pack-install-failed": "Installation failed — please try again.",
        "err-invalid-name": "Please provide a name (max. 60 characters).",
        "err-invalid-url": "The URL is invalid.",
        "err-url-https": "Only https URLs are allowed.",
        "err-style-not-json": "That is not valid JSON.",
        "err-style-version": "The style must have \"version\": 8 (MapLibre Style Spec).",
        "err-style-layers": "The style is missing its \"layers\" array.",
        "err-style-sources": "The style is missing its \"sources\" object.",
        "err-style-too-large": "The style is too large (max. 512 KB).",
        "err-pack-limit": "Maximum of 20 custom packs.",

        "register": "Register",
        "email": "Email",
        "password": "Password",
        "password-min8": "Password (min. 8 characters)",
        "err-invalid-email": "Please enter a valid email address.",
        "err-password-too-short": "Password must be at least 8 characters.",
        "err-email-taken": "This email is already registered.",
        "err-invalid-credentials": "Email or password is incorrect.",
        "err-too-many-requests": "Too many attempts — please wait a moment.",
        "err-unknown": "Something went wrong — please try again.",

        "cat-restaurant": "Restaurants",
        "cat-cafe": "Cafés",
        "cat-supermarket": "Supermarkets",
        "cat-fuel": "Gas stations",
        "cat-pharmacy": "Pharmacies",
        "cat-hotel": "Hotels",
        "cat-parking": "Parking",
        "cat-atm": "ATMs",
        "search-this-area": "Search this area",
        "race-mode": "Race",
        "race-start": "Start race",
        "free-drive": "Free drive",
        "free-drive-start": "Start driving",
        "free-drive-hint": "Drive freely — touch pads. No route needed.",
        "race-pause": "Pause",
        "race-resume": "Resume",
        "race-finish": "Finish",
        "race-again": "Race again",
        "race-brake": "Brake",
        "race-go": "Go",
        "race-left": "Left",
        "race-right": "Right",
        "race-hint": "Camera follows the car at street level. Use touch pads to drive.",
        "race-countdown": "Starting in",
        "race-complete": "Run complete",
        "race-recent": "Recent runs",
        "race-active-hint": "Race mode active — HUD is on the map.",
        "race-empty-runs": "No runs yet.",
    ]

    private static let fr: [String: String] = [
        "cancel": "Annuler",
        "done": "Terminé",
        "more": "Plus",
        "close": "Fermer",
        "retry": "Réessayer",
        "language": "Langue",
        "account": "Compte",
        "sign-in": "Se connecter",
        "sign-out": "Se déconnecter",
        "map-style": "Style de carte",
        "saved-places": "Lieux enregistrés",
        "my-location": "Ma position",
        "view-3d": "Vue 3D",
        "map-load-failed": "Impossible de charger la carte.",

        "search-placeholder": "Rechercher un lieu, une adresse …",
        "search-clear": "Effacer la recherche",
        "recent-searches": "Recherches récentes",
        "results": "Résultats",
        "unknown-place": "Lieu inconnu",

        "route-to-here": "Itinéraire vers ici",
        "share-place": "Partager le lieu",
        "save-place": "Enregistrer le lieu",
        "saved-remove": "Enregistré — retirer",

        "route-pick-start": "Choisissez un point de départ : recherchez ou touchez la carte …",
        "route-swap": "Inverser départ et destination",
        "route-loading": "Calcul de l’itinéraire …",
        "route-err-no-location": "Position indisponible — choisissez un point de départ ou autorisez la localisation.",
        "route-err-not-found": "Aucun itinéraire trouvé.",
        "route-err-unavailable": "Le calcul d'itinéraire est actuellement indisponible.",
        "nav-start": "Démarrer la navigation",
        "nav-stop": "Terminer la navigation",
        "nav-continue": "Continuer",
        "off-route": "Hors itinéraire — recalcul en cours …",
        "current-position": "Position actuelle",
        "mode-car": "Voiture",
        "mode-bike": "Vélo",
        "mode-foot": "À pied",

        "saved-signin-hint": "Connectez-vous pour enregistrer des lieux et les retrouver sur tous vos appareils.",
        "saved-empty": "Rien d’enregistré pour l’instant. Recherchez un lieu et touchez l’étoile.",
        "delete": "Supprimer",

        "install": "Installer",
        "remove": "retirer",
        "name": "Nom",
        "pack-install-title": "Installer un pack de textures",
        "pack-install-hint": "Un pack est un style MapLibre (style.json). Les packs peuvent charger des tuiles/polices externes — n’installez que des styles provenant de sources de confiance.",
        "pack-install-name-placeholder": "p. ex. Neon Nights",
        "tab-from-url": "Depuis une URL",
        "tab-paste-json": "Coller du JSON",
        "style-url-label": "URL du style (https)",
        "style-json-label": "Contenu de style.json",
        "packs-signin-hint": "Connectez-vous pour installer vos propres packs.",
        "pack-install-failed": "Échec de l’installation — veuillez réessayer.",
        "err-invalid-name": "Veuillez indiquer un nom (60 caractères max.).",
        "err-invalid-url": "L’URL est invalide.",
        "err-url-https": "Seules les URL https sont autorisées.",
        "err-style-not-json": "Ce n’est pas du JSON valide.",
        "err-style-version": "Le style doit contenir \"version\": 8 (MapLibre Style Spec).",
        "err-style-layers": "Le style n’a pas de tableau \"layers\".",
        "err-style-sources": "Le style n’a pas d’objet \"sources\".",
        "err-style-too-large": "Le style est trop volumineux (512 Ko max.).",
        "err-pack-limit": "Maximum 20 packs personnalisés.",

        "register": "S’inscrire",
        "email": "E-mail",
        "password": "Mot de passe",
        "password-min8": "Mot de passe (min. 8 caractères)",
        "err-invalid-email": "Veuillez saisir une adresse e-mail valide.",
        "err-password-too-short": "Le mot de passe doit contenir au moins 8 caractères.",
        "err-email-taken": "Cette adresse e-mail est déjà enregistrée.",
        "err-invalid-credentials": "E-mail ou mot de passe incorrect.",
        "err-too-many-requests": "Trop de tentatives — veuillez patienter un instant.",
        "err-unknown": "Une erreur est survenue — veuillez réessayer.",

        "cat-restaurant": "Restaurants",
        "cat-cafe": "Cafés",
        "cat-supermarket": "Supermarchés",
        "cat-fuel": "Stations-service",
        "cat-pharmacy": "Pharmacies",
        "cat-hotel": "Hôtels",
        "cat-parking": "Stationnement",
        "cat-atm": "Distributeurs",
        "search-this-area": "Rechercher dans cette zone",
        "race-mode": "Course",
        "race-start": "Démarrer la course",
        "race-pause": "Pause",
        "race-resume": "Reprendre",
        "race-finish": "Arrivée",
        "race-again": "Rejouer",
        "race-brake": "Frein",
        "race-go": "Gaz",
        "race-left": "Gauche",
        "race-right": "Droite",
        "race-hint": "La caméra suit la route au niveau de la rue. Utilisez les pads tactiles.",
        "race-countdown": "Départ dans",
        "race-complete": "Course terminée",
        "race-recent": "Courses récentes",
        "race-active-hint": "Mode course actif — HUD sur la carte.",
        "race-empty-runs": "Aucune course pour l’instant.",
    ]

    private static let es: [String: String] = [
        "cancel": "Cancelar",
        "done": "Hecho",
        "more": "Más",
        "close": "Cerrar",
        "retry": "Reintentar",
        "language": "Idioma",
        "account": "Cuenta",
        "sign-in": "Iniciar sesión",
        "sign-out": "Cerrar sesión",
        "map-style": "Estilo de mapa",
        "saved-places": "Lugares guardados",
        "my-location": "Mi ubicación",
        "view-3d": "Vista 3D",
        "map-load-failed": "No se pudo cargar el mapa.",

        "search-placeholder": "Buscar lugar, dirección …",
        "search-clear": "Borrar búsqueda",
        "recent-searches": "Búsquedas recientes",
        "results": "Resultados",
        "unknown-place": "Lugar desconocido",

        "route-to-here": "Ruta hasta aquí",
        "share-place": "Compartir lugar",
        "save-place": "Guardar lugar",
        "saved-remove": "Guardado — quitar",

        "route-pick-start": "Elige un punto de partida: busca o toca el mapa …",
        "route-swap": "Intercambiar origen y destino",
        "route-loading": "Calculando ruta …",
        "route-err-no-location": "Ubicación no disponible — elige un punto de partida o permite el acceso a la ubicación.",
        "route-err-not-found": "No se encontró ninguna ruta.",
        "route-err-unavailable": "El cálculo de rutas no está disponible en este momento.",
        "nav-start": "Iniciar navegación",
        "nav-stop": "Finalizar navegación",
        "nav-continue": "Continuar",
        "off-route": "Fuera de ruta — recalculando …",
        "current-position": "Posición actual",
        "mode-car": "Coche",
        "mode-bike": "Bicicleta",
        "mode-foot": "A pie",

        "saved-signin-hint": "Inicia sesión para guardar lugares y verlos en todos tus dispositivos.",
        "saved-empty": "Aún no hay nada guardado. Busca un lugar y toca la estrella.",
        "delete": "Eliminar",

        "install": "Instalar",
        "remove": "quitar",
        "name": "Nombre",
        "pack-install-title": "Instalar pack de texturas",
        "pack-install-hint": "Un pack es un estilo de MapLibre (style.json). Los packs pueden cargar teselas/fuentes externas — instala solo estilos de fuentes de confianza.",
        "pack-install-name-placeholder": "p. ej. Neon Nights",
        "tab-from-url": "Desde URL",
        "tab-paste-json": "Pegar JSON",
        "style-url-label": "URL del estilo (https)",
        "style-json-label": "Contenido de style.json",
        "packs-signin-hint": "Inicia sesión para instalar tus propios packs.",
        "pack-install-failed": "La instalación falló — inténtalo de nuevo.",
        "err-invalid-name": "Indica un nombre (máx. 60 caracteres).",
        "err-invalid-url": "La URL no es válida.",
        "err-url-https": "Solo se permiten URL https.",
        "err-style-not-json": "Eso no es JSON válido.",
        "err-style-version": "El estilo debe tener \"version\": 8 (MapLibre Style Spec).",
        "err-style-layers": "Al estilo le falta el array \"layers\".",
        "err-style-sources": "Al estilo le falta el objeto \"sources\".",
        "err-style-too-large": "El estilo es demasiado grande (máx. 512 KB).",
        "err-pack-limit": "Máximo 20 packs propios.",

        "register": "Registrarse",
        "email": "Correo electrónico",
        "password": "Contraseña",
        "password-min8": "Contraseña (mín. 8 caracteres)",
        "err-invalid-email": "Introduce una dirección de correo válida.",
        "err-password-too-short": "La contraseña debe tener al menos 8 caracteres.",
        "err-email-taken": "Este correo ya está registrado.",
        "err-invalid-credentials": "Correo o contraseña incorrectos.",
        "err-too-many-requests": "Demasiados intentos — espera un momento.",
        "err-unknown": "Algo salió mal — inténtalo de nuevo.",

        "cat-restaurant": "Restaurantes",
        "cat-cafe": "Cafeterías",
        "cat-supermarket": "Supermercados",
        "cat-fuel": "Gasolineras",
        "cat-pharmacy": "Farmacias",
        "cat-hotel": "Hoteles",
        "cat-parking": "Aparcamiento",
        "cat-atm": "Cajeros",
        "search-this-area": "Buscar en esta zona",
        "race-mode": "Carrera",
        "race-start": "Iniciar carrera",
        "race-pause": "Pausa",
        "race-resume": "Reanudar",
        "race-finish": "Meta",
        "race-again": "Otra vez",
        "race-brake": "Freno",
        "race-go": "Acelerar",
        "race-left": "Izquierda",
        "race-right": "Derecha",
        "race-hint": "La cámara sigue la ruta a nivel de calle. Usa los pads táctiles.",
        "race-countdown": "Empieza en",
        "race-complete": "Carrera terminada",
        "race-recent": "Carreras recientes",
        "race-active-hint": "Modo carrera activo — HUD en el mapa.",
        "race-empty-runs": "Aún no hay carreras.",
    ]

    private static let it: [String: String] = [
        "cancel": "Annulla",
        "done": "Fine",
        "more": "Altro",
        "close": "Chiudi",
        "retry": "Riprova",
        "language": "Lingua",
        "account": "Account",
        "sign-in": "Accedi",
        "sign-out": "Esci",
        "map-style": "Stile mappa",
        "saved-places": "Luoghi salvati",
        "my-location": "La mia posizione",
        "view-3d": "Vista 3D",
        "map-load-failed": "Impossibile caricare la mappa.",

        "search-placeholder": "Cerca luogo, indirizzo …",
        "search-clear": "Cancella ricerca",
        "recent-searches": "Ricerche recenti",
        "results": "Risultati",
        "unknown-place": "Luogo sconosciuto",

        "route-to-here": "Percorso fino a qui",
        "share-place": "Condividi luogo",
        "save-place": "Salva luogo",
        "saved-remove": "Salvato — rimuovi",

        "route-pick-start": "Scegli un punto di partenza: cerca o tocca la mappa …",
        "route-swap": "Scambia partenza e destinazione",
        "route-loading": "Calcolo del percorso …",
        "route-err-no-location": "Posizione non disponibile — scegli un punto di partenza o consenti l'accesso alla posizione.",
        "route-err-not-found": "Nessun percorso trovato.",
        "route-err-unavailable": "Il calcolo del percorso non è al momento disponibile.",
        "nav-start": "Avvia navigazione",
        "nav-stop": "Termina navigazione",
        "nav-continue": "Continua",
        "off-route": "Fuori percorso — ricalcolo …",
        "current-position": "Posizione attuale",
        "mode-car": "Auto",
        "mode-bike": "Bici",
        "mode-foot": "A piedi",

        "saved-signin-hint": "Accedi per salvare i luoghi e vederli su tutti i tuoi dispositivi.",
        "saved-empty": "Ancora nulla di salvato. Cerca un luogo e tocca la stella.",
        "delete": "Elimina",

        "install": "Installa",
        "remove": "rimuovi",
        "name": "Nome",
        "pack-install-title": "Installa texture pack",
        "pack-install-hint": "Un pack è uno stile MapLibre (style.json). I pack possono caricare tile/font esterni — installa solo stili da fonti di cui ti fidi.",
        "pack-install-name-placeholder": "es. Neon Nights",
        "tab-from-url": "Da URL",
        "tab-paste-json": "Incolla JSON",
        "style-url-label": "URL dello stile (https)",
        "style-json-label": "Contenuto di style.json",
        "packs-signin-hint": "Accedi per installare i tuoi pack.",
        "pack-install-failed": "Installazione non riuscita — riprova.",
        "err-invalid-name": "Inserisci un nome (max 60 caratteri).",
        "err-invalid-url": "L’URL non è valido.",
        "err-url-https": "Sono consentiti solo URL https.",
        "err-style-not-json": "Questo non è JSON valido.",
        "err-style-version": "Lo stile deve avere \"version\": 8 (MapLibre Style Spec).",
        "err-style-layers": "Allo stile manca l’array \"layers\".",
        "err-style-sources": "Allo stile manca l’oggetto \"sources\".",
        "err-style-too-large": "Lo stile è troppo grande (max 512 KB).",
        "err-pack-limit": "Massimo 20 pack personali.",

        "register": "Registrati",
        "email": "Email",
        "password": "Password",
        "password-min8": "Password (min. 8 caratteri)",
        "err-invalid-email": "Inserisci un indirizzo email valido.",
        "err-password-too-short": "La password deve avere almeno 8 caratteri.",
        "err-email-taken": "Questa email è già registrata.",
        "err-invalid-credentials": "Email o password errata.",
        "err-too-many-requests": "Troppi tentativi — attendi un momento.",
        "err-unknown": "Qualcosa è andato storto — riprova.",

        "cat-restaurant": "Ristoranti",
        "cat-cafe": "Caffè",
        "cat-supermarket": "Supermercati",
        "cat-fuel": "Distributori",
        "cat-pharmacy": "Farmacie",
        "cat-hotel": "Hotel",
        "cat-parking": "Parcheggi",
        "cat-atm": "Bancomat",
        "search-this-area": "Cerca in questa zona",
        "race-mode": "Gara",
        "race-start": "Inizia gara",
        "race-pause": "Pausa",
        "race-resume": "Riprendi",
        "race-finish": "Traguardo",
        "race-again": "Di nuovo",
        "race-brake": "Freno",
        "race-go": "Acceleratore",
        "race-left": "Sinistra",
        "race-right": "Destra",
        "race-hint": "La camera segue il percorso a livello strada. Usa i pad touch.",
        "race-countdown": "Partenza tra",
        "race-complete": "Gara completata",
        "race-recent": "Gare recenti",
        "race-active-hint": "Modalità gara attiva — HUD sulla mappa.",
        "race-empty-runs": "Nessuna gara ancora.",
    ]

    private static let nl: [String: String] = [
        "cancel": "Annuleren",
        "done": "Gereed",
        "more": "Meer",
        "close": "Sluiten",
        "retry": "Opnieuw proberen",
        "language": "Taal",
        "account": "Account",
        "sign-in": "Inloggen",
        "sign-out": "Uitloggen",
        "map-style": "Kaartstijl",
        "saved-places": "Opgeslagen plaatsen",
        "my-location": "Mijn locatie",
        "view-3d": "3D-weergave",
        "map-load-failed": "Kaart kon niet worden geladen.",

        "search-placeholder": "Zoek plaats, adres …",
        "search-clear": "Zoekopdracht wissen",
        "recent-searches": "Recente zoekopdrachten",
        "results": "Resultaten",
        "unknown-place": "Onbekende plaats",

        "route-to-here": "Route hierheen",
        "share-place": "Plaats delen",
        "save-place": "Plaats opslaan",
        "saved-remove": "Opgeslagen — verwijderen",

        "route-pick-start": "Kies een startpunt: zoek of tik op de kaart …",
        "route-swap": "Start en bestemming omwisselen",
        "route-loading": "Route wordt berekend …",
        "route-err-no-location": "Locatie niet beschikbaar — kies een startpunt of sta locatietoegang toe.",
        "route-err-not-found": "Geen route gevonden.",
        "route-err-unavailable": "Routeberekening is momenteel niet beschikbaar.",
        "nav-start": "Navigatie starten",
        "nav-stop": "Navigatie beëindigen",
        "nav-continue": "Doorgaan",
        "off-route": "Van de route af — opnieuw berekenen …",
        "current-position": "Huidige positie",
        "mode-car": "Auto",
        "mode-bike": "Fiets",
        "mode-foot": "Te voet",

        "saved-signin-hint": "Log in om plaatsen op te slaan en op al je apparaten te zien.",
        "saved-empty": "Nog niets opgeslagen. Zoek een plaats en tik op de ster.",
        "delete": "Verwijderen",

        "install": "Installeren",
        "remove": "verwijderen",
        "name": "Naam",
        "pack-install-title": "Texture-pack installeren",
        "pack-install-hint": "Een pack is een MapLibre-stijl (style.json). Packs kunnen externe tegels/lettertypen laden — installeer alleen stijlen uit bronnen die je vertrouwt.",
        "pack-install-name-placeholder": "bijv. Neon Nights",
        "tab-from-url": "Via URL",
        "tab-paste-json": "JSON plakken",
        "style-url-label": "Stijl-URL (https)",
        "style-json-label": "Inhoud van style.json",
        "packs-signin-hint": "Log in om eigen packs te installeren.",
        "pack-install-failed": "Installatie mislukt — probeer het opnieuw.",
        "err-invalid-name": "Geef een naam op (max. 60 tekens).",
        "err-invalid-url": "De URL is ongeldig.",
        "err-url-https": "Alleen https-URL’s zijn toegestaan.",
        "err-style-not-json": "Dit is geen geldige JSON.",
        "err-style-version": "De stijl moet \"version\": 8 hebben (MapLibre Style Spec).",
        "err-style-layers": "De stijl mist de \"layers\"-array.",
        "err-style-sources": "De stijl mist het \"sources\"-object.",
        "err-style-too-large": "De stijl is te groot (max. 512 KB).",
        "err-pack-limit": "Maximaal 20 eigen packs.",

        "register": "Registreren",
        "email": "E-mail",
        "password": "Wachtwoord",
        "password-min8": "Wachtwoord (min. 8 tekens)",
        "err-invalid-email": "Voer een geldig e-mailadres in.",
        "err-password-too-short": "Wachtwoord moet minstens 8 tekens bevatten.",
        "err-email-taken": "Dit e-mailadres is al geregistreerd.",
        "err-invalid-credentials": "E-mailadres of wachtwoord is onjuist.",
        "err-too-many-requests": "Te veel pogingen — wacht heel even.",
        "err-unknown": "Er is iets misgegaan — probeer het opnieuw.",

        "cat-restaurant": "Restaurants",
        "cat-cafe": "Cafés",
        "cat-supermarket": "Supermarkten",
        "cat-fuel": "Tankstations",
        "cat-pharmacy": "Apotheken",
        "cat-hotel": "Hotels",
        "cat-parking": "Parkeren",
        "cat-atm": "Geldautomaten",
        "search-this-area": "In dit gebied zoeken",
        "race-mode": "Race",
        "race-start": "Race starten",
        "race-pause": "Pauze",
        "race-resume": "Hervatten",
        "race-finish": "Finish",
        "race-again": "Opnieuw",
        "race-brake": "Rem",
        "race-go": "Gas",
        "race-left": "Links",
        "race-right": "Rechts",
        "race-hint": "Camera volgt de route op straatniveau. Gebruik de touchpads.",
        "race-countdown": "Start over",
        "race-complete": "Race voltooid",
        "race-recent": "Recente races",
        "race-active-hint": "Racemodus actief — HUD op de kaart.",
        "race-empty-runs": "Nog geen races.",
    ]

    private static let pl: [String: String] = [
        "cancel": "Anuluj",
        "done": "Gotowe",
        "more": "Więcej",
        "close": "Zamknij",
        "retry": "Spróbuj ponownie",
        "language": "Język",
        "account": "Konto",
        "sign-in": "Zaloguj się",
        "sign-out": "Wyloguj się",
        "map-style": "Styl mapy",
        "saved-places": "Zapisane miejsca",
        "my-location": "Moja lokalizacja",
        "view-3d": "Widok 3D",
        "map-load-failed": "Nie udało się wczytać mapy.",

        "search-placeholder": "Szukaj miejsca, adresu …",
        "search-clear": "Wyczyść wyszukiwanie",
        "recent-searches": "Ostatnie wyszukiwania",
        "results": "Wyniki",
        "unknown-place": "Nieznane miejsce",

        "route-to-here": "Trasa tutaj",
        "share-place": "Udostępnij miejsce",
        "save-place": "Zapisz miejsce",
        "saved-remove": "Zapisano — usuń",

        "route-pick-start": "Wybierz punkt startowy: wyszukaj lub dotknij mapy …",
        "route-swap": "Zamień start i cel",
        "route-loading": "Obliczanie trasy …",
        "route-err-no-location": "Lokalizacja niedostępna — wybierz punkt startowy lub zezwól na dostęp do lokalizacji.",
        "route-err-not-found": "Nie znaleziono trasy.",
        "route-err-unavailable": "Wyznaczanie trasy jest obecnie niedostępne.",
        "nav-start": "Rozpocznij nawigację",
        "nav-stop": "Zakończ nawigację",
        "nav-continue": "Dalej",
        "off-route": "Poza trasą — przeliczanie …",
        "current-position": "Obecna pozycja",
        "mode-car": "Samochód",
        "mode-bike": "Rower",
        "mode-foot": "Pieszo",

        "saved-signin-hint": "Zaloguj się, aby zapisywać miejsca i widzieć je na wszystkich urządzeniach.",
        "saved-empty": "Nic jeszcze nie zapisano. Wyszukaj miejsce i dotknij gwiazdki.",
        "delete": "Usuń",

        "install": "Zainstaluj",
        "remove": "usuń",
        "name": "Nazwa",
        "pack-install-title": "Zainstaluj paczkę tekstur",
        "pack-install-hint": "Paczka to styl MapLibre (style.json). Paczki mogą wczytywać zewnętrzne kafelki/czcionki — instaluj tylko style z zaufanych źródeł.",
        "pack-install-name-placeholder": "np. Neon Nights",
        "tab-from-url": "Z adresu URL",
        "tab-paste-json": "Wklej JSON",
        "style-url-label": "Adres URL stylu (https)",
        "style-json-label": "Zawartość style.json",
        "packs-signin-hint": "Zaloguj się, aby instalować własne paczki.",
        "pack-install-failed": "Instalacja nie powiodła się — spróbuj ponownie.",
        "err-invalid-name": "Podaj nazwę (maks. 60 znaków).",
        "err-invalid-url": "Adres URL jest nieprawidłowy.",
        "err-url-https": "Dozwolone są tylko adresy https.",
        "err-style-not-json": "To nie jest prawidłowy JSON.",
        "err-style-version": "Styl musi mieć \"version\": 8 (MapLibre Style Spec).",
        "err-style-layers": "W stylu brakuje tablicy \"layers\".",
        "err-style-sources": "W stylu brakuje obiektu \"sources\".",
        "err-style-too-large": "Styl jest za duży (maks. 512 KB).",
        "err-pack-limit": "Maksymalnie 20 własnych paczek.",

        "register": "Zarejestruj się",
        "email": "E-mail",
        "password": "Hasło",
        "password-min8": "Hasło (min. 8 znaków)",
        "err-invalid-email": "Podaj prawidłowy adres e-mail.",
        "err-password-too-short": "Hasło musi mieć co najmniej 8 znaków.",
        "err-email-taken": "Ten adres e-mail jest już zarejestrowany.",
        "err-invalid-credentials": "Nieprawidłowy e-mail lub hasło.",
        "err-too-many-requests": "Zbyt wiele prób — poczekaj chwilę.",
        "err-unknown": "Coś poszło nie tak — spróbuj ponownie.",

        "cat-restaurant": "Restauracje",
        "cat-cafe": "Kawiarnie",
        "cat-supermarket": "Supermarkety",
        "cat-fuel": "Stacje paliw",
        "cat-pharmacy": "Apteki",
        "cat-hotel": "Hotele",
        "cat-parking": "Parkingi",
        "cat-atm": "Bankomaty",
        "search-this-area": "Szukaj w tym obszarze",
        "race-mode": "Wyścig",
        "race-start": "Start wyścigu",
        "race-pause": "Pauza",
        "race-resume": "Wznów",
        "race-finish": "Meta",
        "race-again": "Jeszcze raz",
        "race-brake": "Hamulec",
        "race-go": "Gaz",
        "race-left": "Lewo",
        "race-right": "Prawo",
        "race-hint": "Kamera podąża trasą na poziomie ulicy. Użyj padów.",
        "race-countdown": "Start za",
        "race-complete": "Wyścig ukończony",
        "race-recent": "Ostatnie wyścigi",
        "race-active-hint": "Tryb wyścigu aktywny — HUD na mapie.",
        "race-empty-runs": "Brak wyścigów.",
    ]

    private static let tr: [String: String] = [
        "cancel": "İptal",
        "done": "Bitti",
        "more": "Daha fazla",
        "close": "Kapat",
        "retry": "Tekrar dene",
        "language": "Dil",
        "account": "Hesap",
        "sign-in": "Giriş yap",
        "sign-out": "Çıkış yap",
        "map-style": "Harita stili",
        "saved-places": "Kayıtlı yerler",
        "my-location": "Konumum",
        "view-3d": "3B görünüm",
        "map-load-failed": "Harita yüklenemedi.",

        "search-placeholder": "Yer, adres ara …",
        "search-clear": "Aramayı temizle",
        "recent-searches": "Son aramalar",
        "results": "Sonuçlar",
        "unknown-place": "Bilinmeyen yer",

        "route-to-here": "Buraya rota",
        "share-place": "Yeri paylaş",
        "save-place": "Yeri kaydet",
        "saved-remove": "Kaydedildi — kaldır",

        "route-pick-start": "Başlangıç noktası seç: ara veya haritaya dokun …",
        "route-swap": "Başlangıç ve varış noktasını değiştir",
        "route-loading": "Rota hesaplanıyor …",
        "route-err-no-location": "Konum kullanılamıyor — bir başlangıç noktası seçin veya konum erişimine izin verin.",
        "route-err-not-found": "Rota bulunamadı.",
        "route-err-unavailable": "Rota hesaplama şu anda kullanılamıyor.",
        "nav-start": "Navigasyonu başlat",
        "nav-stop": "Navigasyonu bitir",
        "nav-continue": "Devam",
        "off-route": "Rota dışında — yeniden hesaplanıyor …",
        "current-position": "Mevcut konum",
        "mode-car": "Araba",
        "mode-bike": "Bisiklet",
        "mode-foot": "Yürüyerek",

        "saved-signin-hint": "Yerleri kaydetmek ve tüm cihazlarında görmek için giriş yap.",
        "saved-empty": "Henüz bir şey kaydedilmedi. Bir yer ara ve yıldıza dokun.",
        "delete": "Sil",

        "install": "Yükle",
        "remove": "kaldır",
        "name": "Ad",
        "pack-install-title": "Doku paketi yükle",
        "pack-install-hint": "Paket, bir MapLibre stilidir (style.json). Paketler harici karolar/yazı tipleri yükleyebilir — yalnızca güvendiğin kaynaklardan stiller yükle.",
        "pack-install-name-placeholder": "örn. Neon Nights",
        "tab-from-url": "URL’den",
        "tab-paste-json": "JSON yapıştır",
        "style-url-label": "Stil URL’si (https)",
        "style-json-label": "style.json içeriği",
        "packs-signin-hint": "Kendi paketlerini yüklemek için giriş yap.",
        "pack-install-failed": "Yükleme başarısız — lütfen tekrar dene.",
        "err-invalid-name": "Lütfen bir ad gir (en fazla 60 karakter).",
        "err-invalid-url": "URL geçersiz.",
        "err-url-https": "Yalnızca https URL’lerine izin verilir.",
        "err-style-not-json": "Bu geçerli bir JSON değil.",
        "err-style-version": "Stil \"version\": 8 içermeli (MapLibre Style Spec).",
        "err-style-layers": "Stilde \"layers\" dizisi eksik.",
        "err-style-sources": "Stilde \"sources\" nesnesi eksik.",
        "err-style-too-large": "Stil çok büyük (en fazla 512 KB).",
        "err-pack-limit": "En fazla 20 özel paket.",

        "register": "Kaydol",
        "email": "E-posta",
        "password": "Şifre",
        "password-min8": "Şifre (en az 8 karakter)",
        "err-invalid-email": "Lütfen geçerli bir e-posta adresi gir.",
        "err-password-too-short": "Şifre en az 8 karakter olmalı.",
        "err-email-taken": "Bu e-posta zaten kayıtlı.",
        "err-invalid-credentials": "E-posta veya şifre hatalı.",
        "err-too-many-requests": "Çok fazla deneme — lütfen biraz bekle.",
        "err-unknown": "Bir şeyler ters gitti — lütfen tekrar dene.",

        "cat-restaurant": "Restoranlar",
        "cat-cafe": "Kafeler",
        "cat-supermarket": "Süpermarketler",
        "cat-fuel": "Benzin istasyonları",
        "cat-pharmacy": "Eczaneler",
        "cat-hotel": "Oteller",
        "cat-parking": "Otopark",
        "cat-atm": "ATM'ler",
        "search-this-area": "Bu bölgede ara",
        "race-mode": "Yarış",
        "race-start": "Yarışı başlat",
        "race-pause": "Duraklat",
        "race-resume": "Devam",
        "race-finish": "Bitiş",
        "race-again": "Tekrar",
        "race-brake": "Fren",
        "race-go": "Gaz",
        "race-left": "Sol",
        "race-right": "Sağ",
        "race-hint": "Kamera rotayı sokak seviyesinde takip eder. Dokunmatik padleri kullan.",
        "race-countdown": "Başlangıç",
        "race-complete": "Yarış tamam",
        "race-recent": "Son yarışlar",
        "race-active-hint": "Yarış modu açık — HUD haritada.",
        "race-empty-runs": "Henüz yarış yok.",
    ]

    private static let dicts: [String: [String: String]] = [
        "de": de, "en": en, "fr": fr, "es": es, "it": it, "nl": nl, "pl": pl, "tr": tr,
    ]
}
